import { NoteData } from '../utils/note-model'
import { isH5 } from '../utils/platform'

function buildExportHtml(note: NoteData): string {
  const mermaidScript = '<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"><\/script>'
  const date = new Date().toISOString().substring(0, 10)
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,viewport-fit=cover"><title>${esc(note.title)}</title>${mermaidScript}<style>${EXPORT_CSS}</style></head>
<body><div class="container"><div class="header"><div class="tag">${esc(note.tag)}</div><div class="title">${esc(note.title)}</div><div class="subtitle">${esc(note.subtitle)}</div></div><div class="tab-bar"><div class="tab-nav"><div class="tab-item active" onclick="switchTab('text',this)">📝 文字</div><div class="tab-item" onclick="switchTab('diagram',this)">🎨 图解</div><div class="tab-item" onclick="switchTab('notes',this)">✏️ 随手记</div></div></div><div class="tab-content active" id="tab-text"><div class="text-content">${note.textContent}</div></div><div class="tab-content" id="tab-diagram">${note.diagramContent}</div><div class="tab-content" id="tab-notes"><div class="section"><textarea class="text-area" placeholder="在这里写下你的思考和笔记...">${esc(note.userNotes)}</textarea></div></div></div><div class="generated-by">Generated by 灵知笔记 &middot; ${date}</div><script>function switchTab(n,e){document.querySelectorAll(".tab-item").forEach(function(t){t.classList.remove("active")});document.querySelectorAll(".tab-content").forEach(function(t){t.classList.remove("active")});e.classList.add("active");document.getElementById("tab-"+n).classList.add("active")} if(typeof mermaid!=="undefined"){mermaid.initialize({startOnLoad:!0,theme:"default"})}<\/script></body></html>`
}

export async function downloadNoteAsHtml(note: NoteData): Promise<void> {
  const html = buildExportHtml(note)
  const filename = `${note.title.replace(/[\\/:*?"<>|]/g, '_')}_${dateStr()}.html`
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })

  if (isH5() && typeof document !== 'undefined') {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }
}

function dateStr(): string {
  return new Date().toISOString().substring(0, 10)
}

const EXPORT_CSS = `
*{margin:0;padding:0;box-sizing:border-box}
html{font-size:15px}
body{font-family:-apple-system,BlinkMacSystemFont,'SF Pro Text','PingFang SC','Helvetica Neue',Arial,sans-serif;background:#f0f2f5;color:#1a2332;line-height:1.7;min-height:100vh;padding:0}
.container{max-width:860px;margin:0 auto;padding:20px 16px 90px}

/* Header */
.header{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);border-radius:16px;padding:24px 28px;margin-bottom:20px;color:#fff;position:relative;overflow:hidden}
.header::before{content:'';position:absolute;top:-50%;right:-20%;width:300px;height:300px;background:rgba(255,255,255,.08);border-radius:50%}
.header::after{content:'';position:absolute;bottom:-30%;left:-10%;width:200px;height:200px;background:rgba(255,255,255,.05);border-radius:50%}
.tag{display:inline-block;background:rgba(255,255,255,.2);backdrop-filter:blur(10px);padding:4px 12px;border-radius:16px;font-size:.7rem;font-weight:600;letter-spacing:.5px;margin-bottom:8px;border:1px solid rgba(255,255,255,.15)}
.title{font-size:1.4rem;font-weight:700;position:relative;z-index:1;line-height:1.3}
.subtitle{font-size:.85rem;opacity:.85;margin-top:6px;position:relative;z-index:1}
.note-source{display:flex;align-items:center;gap:6px;margin-top:6px;position:relative;z-index:1;flex-wrap:wrap}
.source-label{font-size:.7rem;color:rgba(255,255,255,.5);white-space:nowrap}
.source-link{font-size:.75rem;color:rgba(255,255,255,.8);text-decoration:none;border-bottom:1px solid rgba(255,255,255,.25);word-break:break-all}

/* Tab bar */
.tab-bar{position:sticky;bottom:0;left:0;right:0;z-index:100;padding:0 16px 12px;background:linear-gradient(to top,#f0f2f5 70%,transparent)}
.tab-nav{max-width:860px;margin:0 auto;display:flex;background:#fff;border-radius:16px;box-shadow:0 -4px 20px rgba(0,0,0,.08),0 2px 12px rgba(0,0,0,.04);overflow:hidden;margin-bottom:0}
.tab-item{flex:1;text-align:center;padding:14px 20px;cursor:pointer;font-size:.95rem;font-weight:600;color:#8896ab;transition:all .3s;position:relative}
.tab-item.active{color:#667eea}
.tab-item.active::after{content:'';position:absolute;bottom:0;left:20%;right:20%;height:3px;background:#667eea;border-radius:3px 3px 0 0}
.tab-content{display:none;padding:0}
.tab-content.active{display:block}

/* Text content */
.text-content{font-size:16px;line-height:1.8;padding:8px 0}
.text-content h2{font-size:22px;font-weight:700;margin:28px 0 12px;padding-bottom:6px;border-bottom:2px solid #eef0f4}
.text-content h3{font-size:19px;font-weight:600;margin:24px 0 10px}
.text-content p{margin:12px 0}
.text-content ul,.text-content ol{padding-left:24px;margin:12px 0}
.text-content li{margin:6px 0}
.text-content blockquote{border-left:3px solid #e8ecf1;padding:8px 16px;margin:16px 0;background:#f8f9fc;border-radius:0 8px 8px 0;color:#5a6a7e;font-style:italic}
.text-content pre{background:#1e1e2e;color:#e0e0e0;padding:16px 20px;border-radius:12px;overflow-x:auto;margin:16px 0;font-size:14px}
.text-content code{font-family:'Courier New',monospace;font-size:14px}
.text-content table{width:100%;border-collapse:collapse;margin:16px 0;font-size:14px}
.text-content th{background:#667eea;color:#fff;padding:10px 14px;text-align:left;font-weight:600}
.text-content td{padding:10px 14px;border-bottom:1px solid #e8ecf1}
.text-content tr:nth-child(even) td{background:#f8f9fc}

/* Highlights */
.highlight-box{border-radius:12px;padding:14px 18px;margin:16px 0;font-size:15px;line-height:1.7}
.highlight-blue{background:#e8f0fe;border-left:4px solid #667eea}
.highlight-green{background:#e8faf0;border-left:4px solid #10b981}
.highlight-orange{background:#fef4e8;border-left:4px solid #f59e0b}

/* Footer tags */
.footer-tags{margin-top:40px;padding-top:24px;border-top:1px solid #e8ecf1;display:flex;flex-wrap:wrap;gap:8px}
.footer-tag{padding:6px 16px;border-radius:100px;font-size:14px;font-weight:500}
.tag-blue{background:#e8f0fe;color:#667eea}
.tag-purple{background:#f0ebff;color:#7c3aed}
.tag-green{background:#e8faf0;color:#10b981}
.tag-orange{background:#fef4e8;color:#f59e0b}

/* Diagram sections */
.diagram-section{background:#fff;border-radius:16px;padding:20px 18px;margin-bottom:16px;box-shadow:0 2px 12px rgba(0,0,0,.06)}
.diagram-section h3{font-size:1.05rem;font-weight:700;margin-bottom:4px}
.diagram-desc{font-size:.85rem;color:#5a6a7e;margin-bottom:12px}
.diagram-grid-3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;margin-top:8px}
.diagram-grid-4{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:10px;margin-top:8px}
.diagram-grid-auto{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px;margin-top:8px}
.grid-card{background:#f8f9fb;border-radius:12px;padding:16px;border:1px solid #eef0f4}
.grid-card-icon{text-align:center;border-width:2px}
.grid-card-label{display:block;font-size:.7rem;font-weight:700;letter-spacing:.5px;color:#667eea;margin-bottom:4px}
.grid-card-emoji{display:block;font-size:1.8rem;margin:4px 0}
.grid-card-title{display:block;font-weight:700;font-size:1rem;color:#1a2332;margin:6px 0 4px}
.grid-card-sub{display:block;font-size:.8rem;color:#4a5a72;margin:4px 0}
.grid-card-desc{display:block;font-size:.85rem;color:#4a5a72;line-height:1.6;margin-top:4px}

/* Steps */
.step-list{display:flex;flex-direction:column;gap:10px;margin-top:8px}
.step-item{display:flex;align-items:center;gap:12px;border-radius:12px;padding:14px 18px;border:1px solid rgba(0,0,0,.05)}
.step-circle{width:32px;height:32px;border-radius:50%;color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:.9rem;flex-shrink:0}
.step-content{flex:1}
.step-title{font-weight:700;color:#1a2332;font-size:.95rem}
.step-tag{font-size:.75rem;font-weight:600;margin-left:6px}
.step-desc{font-size:.85rem;color:#4a5a72;margin-top:2px}

/* CSS Flow */
.css-flow{display:flex;flex-direction:column;align-items:center;gap:4px;margin:16px 0}
.css-flow-row{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap}
.css-node{display:inline-block;padding:8px 18px;border-radius:30px;font-size:.85rem;font-weight:600;white-space:nowrap;box-shadow:0 2px 6px rgba(0,0,0,.04)}
.css-node.blue{background:#e8f0fe;border:2px solid #667eea;color:#1a5fb4}
.css-node.green{background:#e6f7ed;border:2px solid #22c55e;color:#1a8c4a}
.css-node.orange{background:#fef4e8;border:2px solid #f59e0b;color:#b45a1a}
.css-arrow{display:inline-block;font-size:1.2rem;color:#667eea;font-weight:700;margin:0 4px}

/* Tag grid */
.tag-grid-2{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:8px}
.tag-card{background:#f8f9fb;border-radius:12px;padding:14px 16px;border:1px solid #eef0f4}
.tag-card-title{display:block;font-weight:700;font-size:.95rem;color:#1a2332;margin-bottom:6px}
.tag-group{display:flex;gap:6px;flex-wrap:wrap}
.tag-pill{display:inline-block;padding:3px 10px;border-radius:8px;font-size:.78rem;font-weight:600}

/* Tree */
.tree-wrap{font-size:.9rem;line-height:1.7;padding:8px 0}
.tree-wrap ul{list-style:none;padding:0;margin:0}
.tree-wrap li{position:relative;padding:3px 0 3px 28px;margin:0}
.tree-wrap>ul>li{padding-left:0}
.tree-wrap>ul>li>.node-root{background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;padding:6px 16px;border-radius:8px;font-weight:700;font-size:1rem;display:inline-block;margin-bottom:6px}
.tree-wrap ul ul{position:relative;margin-left:14px;border-left:2px solid #d0d5e0}
.tree-wrap ul ul li::before{content:'';position:absolute;left:-2px;top:12px;width:20px;height:0;border-top:2px solid #d0d5e0}
.tree-wrap ul ul li:last-child::after{content:'';position:absolute;left:-2px;top:12px;bottom:0;width:2px;background:#f0f2f5}
.node-label{background:#f0f4fe;color:#1a5fb4;padding:2px 12px;border-radius:6px;display:inline-block;font-weight:500;font-size:.88rem}
.node-label .arrow{color:#a0aec0;margin:0 4px;font-weight:300}
.node-leaf{background:#f0fff4;color:#276749;padding:2px 12px;border-radius:6px;display:inline-block;font-weight:500;font-size:.88rem}
.tree-tag{font-size:.75rem;padding:1px 8px;border-radius:4px;margin-left:4px;font-weight:600}

/* Bars */
.effect-bar{margin-top:12px;padding:10px 14px;background:#e6f7ed;border-radius:10px;font-size:.85rem;color:#1a8c4a;text-align:center;font-weight:600}
.info-bar{margin-top:12px;padding:10px 14px;background:#f8f9fb;border-radius:10px;border:1px solid #eef0f4;font-size:.85rem;color:#4a5a72}
.bar-sep{color:#d0d5dd;margin:0 6px}

/* Mermaid */
.mermaid{background:#f8f9fc;border-radius:12px;padding:16px;margin-top:8px;text-align:center;overflow-x:auto;font-size:.85rem}
.mermaid svg{max-width:100%;height:auto}
.mermaid-save-hint{text-align:center;font-size:.75rem;color:#a0aec0;margin-top:4px}

/* Misc */
.section{background:#fff;border-radius:16px;padding:24px;margin-bottom:16px;box-shadow:0 2px 12px rgba(0,0,0,.06)}
.text-area{width:100%;min-height:300px;padding:20px;background:#fafbfc;border:2px dashed #e8ecf1;border-radius:12px;font-size:16px;line-height:1.8;resize:vertical}
.generated-by{text-align:center;padding:40px 0 20px;font-size:.8rem;color:#ccc}

/* Responsive */
@media(max-width:600px){.diagram-grid-3,.diagram-grid-4{grid-template-columns:1fr}.tag-grid-2{grid-template-columns:1fr}.container{padding:16px 12px 40px}}
`